#ifndef Raw_Shared_Attribute_Update_h
#define Raw_Shared_Attribute_Update_h

// Local includes.
#include "Raw_Attribute_Callback.h"
#include "IAPI_Implementation.h"

// Library includes.
#include <string.h>


uint8_t constexpr MAX_RAW_ATT_REQUEST_TOPIC_SIZE = 50U;  // v1/devices/me/attributes/response/999 = 42 chars + null
// Log messages.
#if !THINGSBOARD_ENABLE_DYNAMIC
char constexpr RAW_SHARED_ATTRIBUTE_UPDATE_SUBSCRIPTIONS[] = "raw shared attribute update";
#endif // !THINGSBOARD_ENABLE_DYNAMIC


/// @brief Handles the internal implementation of the ThingsBoard shared attribute update API with raw value extraction.
/// Unlike Shared_Attribute_Update, this API does NOT fully parse nested JSON structures.
/// Instead, it performs minimal outer-level parsing and extracts the raw string value for specific attribute keys.
/// This is useful for attributes containing complex nested JSON (e.g., device configurations) that would otherwise
/// exceed the StaticJsonDocument capacity or require excessive memory allocation.
/// See https://thingsboard.io/docs/reference/mqtt-api/#subscribe-to-attribute-updates-from-the-server for more information
/// @tparam Logger Implementation that should be used to print error messages generated by internal processes and additional debugging messages if THINGSBOARD_ENABLE_DEBUG is set, default = DefaultLogger
#if THINGSBOARD_ENABLE_DYNAMIC
template <typename Logger = DefaultLogger>
#else
/// @tparam MaxSubscriptions Maximum amount of simultaneous raw shared attribute update subscriptions.
/// Once the maximum amount has been reached it is not possible to increase the size, this is done because it allows to allocate the memory on the stack instead of the heap, default = Default_Subscriptions_Amount (1)
template<size_t MaxSubscriptions = Default_Subscriptions_Amount, typename Logger = DefaultLogger>
#endif // THINGSBOARD_ENABLE_DYNAMIC
class Raw_Shared_Attribute_Update : public IAPI_Implementation {
  public:
        enum class Extract_Failure_Reason : uint8_t {
                NONE = 0,
                INVALID_ARGUMENT,
                KEY_TOO_LONG,
                KEY_NOT_FOUND,
                COLON_NOT_FOUND,
                VALUE_START_INVALID,
                VALUE_END_NOT_FOUND
        };

    /// @brief Constructor
    Raw_Shared_Attribute_Update()
      : m_subscribe_topic_callback()
      , m_unsubscribe_topic_callback()
      , m_send_json_string_callback()
      , m_get_request_id_callback()
      , m_response_topic()
      , m_raw_callbacks()
    {
        // Can be ignored, because the topic is set correctly once we start a request anyway.
        (void)snprintf(m_response_topic, sizeof(m_response_topic), ATTRIBUTE_RESPONSE_TOPIC, 0U);
    }

    ~Raw_Shared_Attribute_Update() override = default;

    /// @brief Subscribes multiple raw attribute callbacks,
    /// that will be called if the key-value pair from the server for the given shared attributes is received.
    /// Unlike the standard Shared_Attribute_Update, this version extracts the raw value string without full JSON parsing.
    /// Can be called even if we are currently not connected to the cloud
    /// @tparam InputIterator Class that points to the begin and end iterator
    /// of the given data container, allows for using / passing either std::vector or std::array
    /// @param first Iterator pointing to the first element in the data container
    /// @param last Iterator pointing to the end of the data container (last element + 1)
    /// @param request_on_subscribe Whether to automatically request the current attribute values when subscribing (default = true)
    /// @return Whether subscribing the given callbacks was successful or not
    template<typename InputIterator>
    bool Raw_Attributes_Subscribe(InputIterator const & first, InputIterator const & last, bool const & request_on_subscribe = true) {
#if !THINGSBOARD_ENABLE_DYNAMIC
        size_t const size = Helper::distance(first, last);
        if (m_raw_callbacks.size() + size > m_raw_callbacks.capacity()) {
            Logger::printfln(MAX_SUBSCRIPTIONS_EXCEEDED, RAW_SHARED_ATTRIBUTE_UPDATE_SUBSCRIPTIONS, MAX_SUBSCRIPTIONS_TEMPLATE_NAME);
            return false;
        }
#endif // !THINGSBOARD_ENABLE_DYNAMIC
        (void)m_subscribe_topic_callback.Call_Callback(ATTRIBUTE_TOPIC);
        
        // Subscribe to request response topic if auto-request is enabled
        if (request_on_subscribe) {
#if THINGSBOARD_ENABLE_DEBUG
            Logger::printfln("[RAW_API] Subscribing to response topic pattern: %s", ATTRIBUTE_RESPONSE_SUBSCRIBE_TOPIC);
#endif
            bool subscribe_result = m_subscribe_topic_callback.Call_Callback(ATTRIBUTE_RESPONSE_SUBSCRIBE_TOPIC);
#if THINGSBOARD_ENABLE_DEBUG
            Logger::printfln("[RAW_API] Response topic subscription %s", subscribe_result ? "succeeded" : "FAILED");
#endif
        }
        
        m_raw_callbacks.insert(m_raw_callbacks.end(), first, last);
        
        // Auto-request current values if enabled
        if (request_on_subscribe) {
            for (auto it = first; it != last; ++it) {
                Request_Attribute(*it);
            }
        }
        
        return true;
    }

    /// @brief Subscribe one raw attribute callback,
    /// that will be called if the key-value pair from the server for the given shared attribute is received.
    /// Unlike the standard Shared_Attribute_Update, this version extracts the raw value string without full JSON parsing.
    /// Can be called even if we are currently not connected to the cloud
    /// @param callback Callback method that will be called
    /// @param request_on_subscribe Whether to automatically request the current attribute value when subscribing (default = true)
    /// @return Whether subscribing the given callback was successful or not
    bool Raw_Attributes_Subscribe(Raw_Attribute_Callback const & callback, bool const & request_on_subscribe = true) {
#if !THINGSBOARD_ENABLE_DYNAMIC
        if (m_raw_callbacks.size() + 1U > m_raw_callbacks.capacity()) {
            Logger::printfln(MAX_SUBSCRIPTIONS_EXCEEDED, RAW_SHARED_ATTRIBUTE_UPDATE_SUBSCRIPTIONS, MAX_SUBSCRIPTIONS_TEMPLATE_NAME);
            return false;
        }
#endif // !THINGSBOARD_ENABLE_DYNAMIC
        (void)m_subscribe_topic_callback.Call_Callback(ATTRIBUTE_TOPIC);
        
        // Subscribe to request response topic if auto-request is enabled
        if (request_on_subscribe) {
#if THINGSBOARD_ENABLE_DEBUG
            Logger::printfln("[RAW_API] Subscribing to response topic pattern: %s", ATTRIBUTE_RESPONSE_SUBSCRIBE_TOPIC);
#endif
            bool subscribe_result = m_subscribe_topic_callback.Call_Callback(ATTRIBUTE_RESPONSE_SUBSCRIBE_TOPIC);
#if THINGSBOARD_ENABLE_DEBUG
            Logger::printfln("[RAW_API] Response topic subscription %s", subscribe_result ? "succeeded" : "FAILED");
#endif
        }
        
        m_raw_callbacks.push_back(callback);
        
        // Auto-request current value if enabled
        if (request_on_subscribe) {
            Request_Attribute(callback);
        }
        
        return true;
    }

    /// @brief Sets a passthrough JSON callback for handling non-raw attribute keys
    /// This allows the RAW API to handle both complex (raw) and simple (JSON) attributes from the same topic.
    /// Keys that are NOT in the raw callbacks list will be passed to this callback as a JsonObjectConst.
    /// @param callback Function that receives JsonObjectConst with non-raw attributes
    void Set_Json_Passthrough_Callback(Callback<void, JsonObjectConst const &>::function callback) {
        m_json_passthrough_callback.Set_Callback(callback);
    }

    /// @brief Unsubcribes all raw attribute callbacks
    /// @return Whether unsubcribing all the previously subscribed callbacks was successful or not
    bool Raw_Attributes_Unsubscribe() {
        m_raw_callbacks.clear();
        // Note: We don't unsubscribe from ATTRIBUTE_TOPIC because regular Shared_Attribute_Update might still be using it
        return true;
    }

    API_Process_Type Get_Process_Type() const override {
        return API_Process_Type::RAW;
    }

    void Process_Response(char const * topic, uint8_t * payload, unsigned int length) override {
#if THINGSBOARD_ENABLE_DEBUG
        Logger::printfln("[RAW_API] Process_Response called on topic='%s', %u raw callbacks registered, m_response_topic='%s'", topic, m_raw_callbacks.size(), m_response_topic);
#endif
        
        // Track which top-level keys were handled by raw callbacks
        // Store actual matched keys (not prefix patterns) in fixed-size buffers
        struct MatchedKey {
            char key[64];
        };
#if THINGSBOARD_ENABLE_DYNAMIC
        Vector<MatchedKey> matched_keys;
#else
        // NOTE: Capacity is NOT tied to MaxSubscriptions (which is for callbacks).
        // A single message can have many top-level keys. On server sync, the device receives
        // ALL configured DEVICE_* attributes at once. Use capacity for ~20 devices + buffer.
        Array<MatchedKey, 32> matched_keys;
#endif
        
        // For prefix matching, we need to enumerate all attribute keys WITHOUT parsing their values
        // Strategy: Lightweight scan for keys, then extract raw values only for matches
        
        // Make a working copy of the payload to avoid corruption during extraction
        char * payload_copy = (char *)malloc(length + 1);
        if (payload_copy == nullptr) {
#if THINGSBOARD_ENABLE_DEBUG
            Logger::printfln("[RAW_API] Failed to allocate payload copy");
#endif
            return;
        }
        memcpy(payload_copy, payload, length);
        payload_copy[length] = '\0';
        
        // Track total number of top-level keys found (for optimization)
        size_t total_keys_found = 0;
        
        // Scan for attribute keys in the payload
        // Format: {"key1": value1, "key2": value2, ...} or {"shared":{"key1":value1,...}}
        char * payload_end = payload_copy + length;
        
        // Check if wrapped in "shared" key (attribute request responses)
        char * search_start = payload_copy;
        char shared_key_pattern[32];
        snprintf(shared_key_pattern, sizeof(shared_key_pattern), "\"%s\"", SHARED_RESPONSE_KEY);
        const char * shared_wrapper = strstr(payload_copy, shared_key_pattern);
        if (shared_wrapper != nullptr) {
            // Find the opening brace of the shared object
            char * shared_brace = strchr((char *)shared_wrapper, '{');
            if (shared_brace != nullptr && shared_brace < payload_end) {
                search_start = shared_brace;
            }
        }
        
        // Character-by-character scan with depth tracking to detect only top-level keys.
        // This avoids false positives from nested keys inside DEVICE_* JSON objects.
        int object_depth = 0;
        int array_depth = 0;
        char * scan_ptr = search_start;
        while (scan_ptr < payload_end) {
            char current = *scan_ptr;

            if (current == '"') {
                // Parse full JSON string token with escape support.
                char * quote_end = scan_ptr + 1;
                bool escape_next = false;
                while (quote_end < payload_end) {
                    if (escape_next) {
                        escape_next = false;
                        quote_end++;
                        continue;
                    }
                    if (*quote_end == '\\') {
                        escape_next = true;
                        quote_end++;
                        continue;
                    }
                    if (*quote_end == '"') {
                        break;
                    }
                    quote_end++;
                }

                if (quote_end >= payload_end) {
                    break;
                }

                // Potential key only at top-level object (depth 1, not inside arrays).
                if (object_depth == 1 && array_depth == 0) {
                    char * after_quote = quote_end + 1;
                    while (after_quote < payload_end && (*after_quote == ' ' || *after_quote == '\t' || *after_quote == '\n' || *after_quote == '\r')) {
                        after_quote++;
                    }

                    if (after_quote < payload_end && *after_quote == ':') {
                        size_t key_len = quote_end - scan_ptr - 1;
                        if (key_len > 0 && key_len < 128) {
                            char key_buffer[128];
                            memcpy(key_buffer, scan_ptr + 1, key_len);
                            key_buffer[key_len] = '\0';

                            // Skip internal wrapper key.
                            if (strcmp(key_buffer, SHARED_RESPONSE_KEY) != 0) {
                                total_keys_found++;

#if THINGSBOARD_ENABLE_DEBUG
                                Logger::printfln("[RAW_API] Found top-level key: '%s'", key_buffer);
#endif

                                for (auto const & callback : m_raw_callbacks) {
                                    if (callback.Matches(key_buffer)) {
#if THINGSBOARD_ENABLE_DEBUG
                                        Logger::printfln("[RAW_API] Callback MATCHED! Extracting raw value from original payload");
#endif
                                        char const * value_start = nullptr;
                                        size_t value_length = 0;
                                        Extract_Failure_Reason failure_reason = Extract_Failure_Reason::NONE;

                                        if (Extract_Attribute_Value((char *)payload, length, key_buffer, &value_start, &value_length, &failure_reason)) {
#if THINGSBOARD_ENABLE_DEBUG
                                            Logger::printfln("[RAW_API] Extracted %u bytes, calling user callback", value_length);
#endif
                                            callback.Call_Callback(key_buffer, value_start, value_length);

                                            MatchedKey mk;
                                            strncpy(mk.key, key_buffer, sizeof(mk.key) - 1);
                                            mk.key[sizeof(mk.key) - 1] = '\0';
                                            matched_keys.push_back(mk);
                                        }
#if THINGSBOARD_ENABLE_DEBUG
                                        else {
                                            Logger::printfln("[RAW_API] Extract_Attribute_Value failed: %s", Get_Extract_Failure_Reason_String(failure_reason));
                                        }
#endif
                                        break;
                                    }
                                }

                                // Skip this key's full value to avoid scanning nested content as additional keys.
                                char * value_start_scan = after_quote + 1;
                                while (value_start_scan < payload_end && (*value_start_scan == ' ' || *value_start_scan == '\t' || *value_start_scan == '\n' || *value_start_scan == '\r')) {
                                    value_start_scan++;
                                }

                                char * value_end_scan = Find_Value_End(value_start_scan, payload_end);
                                if (value_end_scan != nullptr && value_end_scan > scan_ptr) {
                                    scan_ptr = value_end_scan;
                                    continue;
                                }
                            }
                        }

                        // Skip this key's full value to avoid scanning nested content as additional keys.
                        char * value_start_scan = after_quote + 1;
                        while (value_start_scan < payload_end && (*value_start_scan == ' ' || *value_start_scan == '\t' || *value_start_scan == '\n' || *value_start_scan == '\r')) {
                            value_start_scan++;
                        }

                        char * value_end_scan = Find_Value_End(value_start_scan, payload_end);
                        if (value_end_scan != nullptr && value_end_scan > scan_ptr) {
                            scan_ptr = value_end_scan;
                            continue;
                        }
                    }
                }

                scan_ptr = quote_end + 1;
                continue;
            }

            if (current == '{') {
                object_depth++;
            } else if (current == '}') {
                object_depth--;
                if (object_depth <= 0) {
                    break;
                }
            } else if (current == '[') {
                array_depth++;
            } else if (current == ']') {
                if (array_depth > 0) {
                    array_depth--;
                }
            }

            scan_ptr++;
        }
        
        free(payload_copy);
        
        // Call passthrough callback with parsed JSON, excluding keys handled by raw callbacks
        // OPTIMIZATION: Skip parsing if ALL top-level keys were matched by raw callbacks
#if THINGSBOARD_ENABLE_DEBUG
        Logger::printfln("[RAW_API] total_keys_found=%u, matched_keys.size()=%u", total_keys_found, matched_keys.size());
#endif
        
        // Always deserialize and pass through ALL attributes to the passthrough callback.
        // This handles both:
        //  - DEVICE_* attributes (matched by prefix, will be processed by raw callbacks)
        //  - Non-DEVICE_* attributes like OUTPUT1, fw_*, etc. (passed to JSON handlers via callback)
        //
        // By deserializing once here and returning, we PREVENT the dispatcher from attempting
        // a second deserialization, which would corrupt the payload buffer with zero-copy null terminators.
        //
        // The passthrough callback forwards ALL attributes to downstream JSON handlers
        // (Shared_Attribute_Update, OTA_Firmware_Update, etc.), which filter based on their
        // own subscriptions. This is safe and memory-efficient.
        
        if (total_keys_found > 0) {
#if THINGSBOARD_ENABLE_DEBUG
            Logger::printfln("[RAW_API] Found %u keys (matched=%u), deserializing and passing through", total_keys_found, matched_keys.size());
#endif
            StaticJsonDocument<1536> doc;
            DeserializationError error = deserializeJson(doc, payload, length);
            if (!error) {
                JsonObjectConst root = doc.as<JsonObjectConst>();
                if (root.containsKey(SHARED_RESPONSE_KEY)) {
                    root = root[SHARED_RESPONSE_KEY];
                }
                
                // Pass ALL attributes to the passthrough callback.
                // This includes both DEVICE_* (handled by raw callbacks) and non-DEVICE_* keys.
                // The callback forwards to downstream JSON handlers which filter per their subscriptions.
                m_json_passthrough_callback.Call_Callback(root);
            }
            return;  // Prevent dispatcher from re-deserializing and corrupting the buffer
        }
    }

    void Process_Json_Response(char const * topic, JsonDocument const & data) override {
        // Not used - we process raw payload in Process_Response
    }

    bool Is_Response_Topic_Matching(char const * topic) const override {
        // Only claim attribute topic if we have raw callbacks registered.
        // This allows normal SDK handlers (like OTA) to process attributes when RAW API isn't needed.
        bool is_update = m_raw_callbacks.size() > 0 && strncmp(ATTRIBUTE_TOPIC, topic, strlen(ATTRIBUTE_TOPIC)) == 0;
        bool is_request_response = strncmp(m_response_topic, topic, strlen(m_response_topic)) == 0;
#if THINGSBOARD_ENABLE_DEBUG
        // Always log attribute-related topics to debug response matching
        if (strstr(topic, "attributes") != nullptr) {
            Logger::printfln("[RAW_API] Topic check: topic='%s', is_update=%u, is_request_response=%u, m_response_topic='%s'", topic, is_update, is_request_response, m_response_topic);
        }
#endif
        return is_update || is_request_response;
    }

    bool Unsubscribe() override {
        return Raw_Attributes_Unsubscribe();
    }

    bool Resubscribe_Permanent_Subscriptions() override {
        if (m_raw_callbacks.empty()) {
            return true;
        }
        return m_subscribe_topic_callback.Call_Callback(ATTRIBUTE_TOPIC);
    }

#if !THINGSBOARD_USE_ESP_TIMER
    void loop() override {
        // Nothing to do
    }
#endif // !THINGSBOARD_USE_ESP_TIMER

    void Initialize() override {
        // Nothing to do
    }

    void Set_Client_Callbacks(Callback<void, IAPI_Implementation &>::function subscribe_api_callback, Callback<bool, char const * const, JsonDocument const &, size_t const &>::function send_json_callback, Callback<bool, char const * const, char const * const>::function send_json_string_callback, Callback<bool, char const * const>::function subscribe_topic_callback, Callback<bool, char const * const>::function unsubscribe_topic_callback, Callback<uint16_t>::function get_receive_size_callback, Callback<uint16_t>::function get_send_size_callback, Callback<bool, uint16_t, uint16_t>::function set_buffer_size_callback, Callback<size_t *>::function get_request_id_callback) override {
        m_subscribe_topic_callback.Set_Callback(subscribe_topic_callback);
        m_unsubscribe_topic_callback.Set_Callback(unsubscribe_topic_callback);
        m_send_json_string_callback.Set_Callback(send_json_string_callback);
        m_get_request_id_callback.Set_Callback(get_request_id_callback);
    }

  private:
    /// @brief Sends an attribute request for a specific callback
    /// @param callback The callback containing the attribute key to request
    /// @return Whether sending the request was successful
    bool Request_Attribute(Raw_Attribute_Callback const & callback) {
        // Get request ID from client
        size_t * p_request_id = m_get_request_id_callback.Call_Callback();
        if (p_request_id == nullptr) {
#if THINGSBOARD_ENABLE_DEBUG
            Logger::printfln("[RAW_API] Request_Attribute: Failed to get request ID");
#endif
            return false;
        }
        auto & request_id = *p_request_id;
        request_id++;

        // Update response topic with current request ID
        (void)snprintf(m_response_topic, sizeof(m_response_topic), ATTRIBUTE_RESPONSE_TOPIC, request_id);

        // Send request for the specific attribute key
        char request_topic[Helper::detectSize(ATTRIBUTE_REQUEST_TOPIC, request_id)] = {};
        (void)snprintf(request_topic, sizeof(request_topic), ATTRIBUTE_REQUEST_TOPIC, request_id);

        char const * attr_key = callback.Get_Attribute_Key();
        char request_payload[128];
        
        if (callback.Is_Prefix()) {
            // For prefix subscriptions, request all attributes (Option A)
            // ThingsBoard API doesn't support prefix-based requests,
            // so we request all and filter client-side using prefix matching
            (void)snprintf(request_payload, sizeof(request_payload), "{}");
#if THINGSBOARD_ENABLE_DEBUG
            Logger::printfln("[RAW_API] Request_Attribute: Requesting prefix '%s', request_id=%u, response_topic=%s", attr_key, request_id, m_response_topic);
#endif
        } else {
            // For exact match subscriptions, request specific attribute
            (void)snprintf(request_payload, sizeof(request_payload), "{\"sharedKeys\":\"%s\"}", attr_key);
#if THINGSBOARD_ENABLE_DEBUG
            Logger::printfln("[RAW_API] Request_Attribute: Requesting exact key '%s', request_id=%u, response_topic=%s", attr_key, request_id, m_response_topic);
#endif
        }

        bool result = m_send_json_string_callback.Call_Callback(request_topic, request_payload);
#if THINGSBOARD_ENABLE_DEBUG
        if (!result) {
            Logger::printfln("[RAW_API] Request_Attribute: Failed to send request");
        }
#endif
        return result;
    }

    /// @brief Extracts the raw value substring for a specific attribute key from the JSON payload
    /// @param payload Full JSON payload as received from MQTT
    /// @param length Total length of payload
    /// @param attr_key Attribute key to search for (e.g., "regCfg")
    /// @param out_value_start Output parameter - pointer to start of value in payload
    /// @param out_value_length Output parameter - length of value in bytes
    /// @return Whether extraction was successful
    bool Extract_Attribute_Value(char * payload, unsigned int length, char const * attr_key, char const ** out_value_start, size_t * out_value_length, Extract_Failure_Reason * out_reason = nullptr) {
        if (out_reason != nullptr) {
            *out_reason = Extract_Failure_Reason::NONE;
        }
        if (payload == nullptr || attr_key == nullptr || out_value_start == nullptr || out_value_length == nullptr || length == 0U) {
            if (out_reason != nullptr) {
                *out_reason = Extract_Failure_Reason::INVALID_ARGUMENT;
            }
            return false;
        }

        // Build search pattern: "attr_key"
        char search_pattern[128];
        int pattern_length = snprintf(search_pattern, sizeof(search_pattern), "\"%s\"", attr_key);
        if (pattern_length <= 0 || static_cast<size_t>(pattern_length) >= sizeof(search_pattern)) {
            if (out_reason != nullptr) {
                *out_reason = Extract_Failure_Reason::KEY_TOO_LONG;
            }
            return false;
        }

        char * payload_end = payload + length;
        
        // Find the attribute key in the payload
        char * key_pos = Find_Substring_Bounded(payload, payload_end, search_pattern, static_cast<size_t>(pattern_length));
        if (key_pos == nullptr) {
            if (out_reason != nullptr) {
                *out_reason = Extract_Failure_Reason::KEY_NOT_FOUND;
            }
            return false;
        }
        
        // Move past the key and find the colon
        char * colon_pos = Find_Char_Bounded(key_pos + pattern_length, payload_end, ':');
        if (colon_pos == nullptr) {
            if (out_reason != nullptr) {
                *out_reason = Extract_Failure_Reason::COLON_NOT_FOUND;
            }
            return false;
        }
        
        // Skip colon and any whitespace
        char * value_start = colon_pos + 1;
        while (value_start < payload_end && (*value_start == ' ' || *value_start == '\t' || *value_start == '\n' || *value_start == '\r')) {
            value_start++;
        }
        
        if (value_start >= payload_end) {
            if (out_reason != nullptr) {
                *out_reason = Extract_Failure_Reason::VALUE_START_INVALID;
            }
            return false;
        }
        
        // Find the end of the value
        char * value_end = Find_Value_End(value_start, payload_end);
        if (value_end == nullptr) {
            if (out_reason != nullptr) {
                *out_reason = Extract_Failure_Reason::VALUE_END_NOT_FOUND;
            }
            return false;
        }
        
        *out_value_start = value_start;
        *out_value_length = value_end - value_start;
        return true;
    }

    char * Find_Substring_Bounded(char * buffer_start, char * buffer_end, char const * pattern, size_t pattern_length) {
        if (buffer_start == nullptr || buffer_end == nullptr || pattern == nullptr || pattern_length == 0U || buffer_start >= buffer_end) {
            return nullptr;
        }

        size_t const buffer_length = static_cast<size_t>(buffer_end - buffer_start);
        if (pattern_length > buffer_length) {
            return nullptr;
        }

        char * search_end = buffer_end - pattern_length;
        for (char * current = buffer_start; current <= search_end; ++current) {
            if (memcmp(current, pattern, pattern_length) == 0) {
                return current;
            }
        }
        return nullptr;
    }

    char * Find_Char_Bounded(char * start, char * end, char needle) {
        if (start == nullptr || end == nullptr || start >= end) {
            return nullptr;
        }

        for (char * current = start; current < end; ++current) {
            if (*current == needle) {
                return current;
            }
        }
        return nullptr;
    }

    static size_t Find_First_Null_Byte(uint8_t const * payload, unsigned int length) {
        if (payload == nullptr || length == 0U) {
            return 0U;
        }
        for (size_t index = 0; index < length; ++index) {
            if (payload[index] == '\0') {
                return index;
            }
        }
        return length;
    }

    char const * Get_Extract_Failure_Reason_String(Extract_Failure_Reason reason) const {
        switch (reason) {
            case Extract_Failure_Reason::NONE:
                return "none";
            case Extract_Failure_Reason::INVALID_ARGUMENT:
                return "invalid-argument";
            case Extract_Failure_Reason::KEY_TOO_LONG:
                return "key-too-long";
            case Extract_Failure_Reason::KEY_NOT_FOUND:
                return "key-not-found";
            case Extract_Failure_Reason::COLON_NOT_FOUND:
                return "colon-not-found";
            case Extract_Failure_Reason::VALUE_START_INVALID:
                return "value-start-invalid";
            case Extract_Failure_Reason::VALUE_END_NOT_FOUND:
                return "value-end-not-found";
            default:
                return "unknown";
        }
    }

    /// @brief Finds the end of a JSON value starting from value_start
    /// Handles objects {}, arrays [], strings "", and primitives (numbers, booleans, null)
    /// @param value_start Pointer to first character of JSON value
    /// @param payload_end Pointer to end of payload (one past last valid byte)
    /// @return Pointer to one past the last character of the value, or nullptr on error
    char * Find_Value_End(char * value_start, char * payload_end) {
        if (value_start >= payload_end) {
            return nullptr;
        }
        
        char first_char = *value_start;
        char * p = value_start;
        
        // Handle different JSON value types
        if (first_char == '{') {
            // Object - track brace depth
            int depth = 0;
            bool in_string = false;
            bool escape_next = false;
            
            while (p < payload_end) {
                if (escape_next) {
                    escape_next = false;
                    p++;
                    continue;
                }
                
                if (*p == '\\') {
                    escape_next = true;
                    p++;
                    continue;
                }
                
                if (*p == '"') {
                    in_string = !in_string;
                }
                else if (!in_string) {
                    if (*p == '{') {
                        depth++;
                    }
                    else if (*p == '}') {
                        depth--;
                        if (depth == 0) {
                            return p + 1;  // Include closing brace
                        }
                    }
                }
                p++;
            }
            return nullptr;  // Unmatched braces
        }
        else if (first_char == '[') {
            // Array - track bracket depth
            int depth = 0;
            bool in_string = false;
            bool escape_next = false;
            
            while (p < payload_end) {
                if (escape_next) {
                    escape_next = false;
                    p++;
                    continue;
                }
                
                if (*p == '\\') {
                    escape_next = true;
                    p++;
                    continue;
                }
                
                if (*p == '"') {
                    in_string = !in_string;
                }
                else if (!in_string) {
                    if (*p == '[') {
                        depth++;
                    }
                    else if (*p == ']') {
                        depth--;
                        if (depth == 0) {
                            return p + 1;  // Include closing bracket
                        }
                    }
                }
                p++;
            }
            return nullptr;  // Unmatched brackets
        }
        else if (first_char == '"') {
            // String - find closing unescaped quote
            p++;  // Skip opening quote
            bool escape_next = false;
            
            while (p < payload_end) {
                if (escape_next) {
                    escape_next = false;
                    p++;
                    continue;
                }
                
                if (*p == '\\') {
                    escape_next = true;
                    p++;
                    continue;
                }
                
                if (*p == '"') {
                    return p + 1;  // Include closing quote
                }
                p++;
            }
            return nullptr;  // Unmatched quote
        }
        else {
            // Number, boolean (true/false), or null - find delimiter
            while (p < payload_end) {
                char c = *p;
                // Value ends at comma, closing brace, closing bracket, or whitespace
                if (c == ',' || c == '}' || c == ']' || c == ' ' || c == '\t' || c == '\n' || c == '\r') {
                    return p;
                }
                p++;
            }
            return p;  // End of payload
        }
    }

    Callback<bool, char const * const>   m_subscribe_topic_callback = {};          // Subscribe mqtt topic client callback
    Callback<bool, char const * const>   m_unsubscribe_topic_callback = {};        // Unsubscribe mqtt topic client callback
    Callback<bool, char const * const, char const * const> m_send_json_string_callback = {};  // Send JSON string client callback
    Callback<size_t *>                   m_get_request_id_callback = {};           // Get request ID client callback
    Callback<void, JsonObjectConst const &> m_json_passthrough_callback = {};      // Passthrough callback for non-raw JSON attributes
    char                                 m_response_topic[MAX_RAW_ATT_REQUEST_TOPIC_SIZE] = {}; // Response topic for attribute requests

#if THINGSBOARD_ENABLE_DYNAMIC
    Vector<Raw_Attribute_Callback>       m_raw_callbacks = {};                     // Raw attribute callbacks array
#else
    Array<Raw_Attribute_Callback, MaxSubscriptions> m_raw_callbacks = {};          // Raw attribute callbacks array
#endif // THINGSBOARD_ENABLE_DYNAMIC
};

#endif // Raw_Shared_Attribute_Update_h
