#ifndef Raw_Attribute_Request_h
#define Raw_Attribute_Request_h

// Local includes.
#include "Raw_Attribute_Callback.h"
#include "IAPI_Implementation.h"

// Library includes.
#include <string.h>


uint8_t constexpr MAX_ATT_REQUEST_TOPIC_SIZE = 33U;
// Log messages.
#if !THINGSBOARD_ENABLE_DYNAMIC
char constexpr RAW_ATTRIBUTE_REQUEST_SUBSCRIPTIONS[] = "raw attribute request";
#endif // !THINGSBOARD_ENABLE_DYNAMIC


/// @brief Handles the internal implementation of the ThingsBoard client-side or shared attribute request API with raw value extraction.
/// Unlike Attribute_Request, this API does NOT fully parse nested JSON structures.
/// Instead, it performs minimal outer-level parsing and extracts the raw string value for specific attribute keys.
/// This is useful for attributes containing complex nested JSON (e.g., device configurations) that would otherwise
/// exceed the StaticJsonDocument capacity or require excessive memory allocation.
/// See https://thingsboard.io/docs/reference/mqtt-api/#request-attribute-values-from-the-server for more information
/// @tparam Logger Implementation that should be used to print error messages generated by internal processes and additional debugging messages if THINGSBOARD_ENABLE_DEBUG is set, default = DefaultLogger
#if THINGSBOARD_ENABLE_DYNAMIC
template <typename Logger = DefaultLogger>
#else
/// @tparam MaxSubscriptions Maximum amount of simultaneous raw attribute request subscriptions.
/// Once the maximum amount has been reached it is not possible to increase the size, default = Default_Subscriptions_Amount (1)
template<size_t MaxSubscriptions = Default_Subscriptions_Amount, typename Logger = DefaultLogger>
#endif // THINGSBOARD_ENABLE_DYNAMIC
class Raw_Attribute_Request : public IAPI_Implementation {
  public:
    /// @brief Constructor
    Raw_Attribute_Request()
      : m_subscribe_topic_callback()
      , m_unsubscribe_topic_callback()
      , m_send_json_string_callback()
      , m_get_request_id_callback()
      , m_response_topic()
      , m_raw_callbacks()
#if !THINGSBOARD_USE_ESP_TIMER
      , m_request_sent_time(0U)
      , m_timeout(0U)
#endif // !THINGSBOARD_USE_ESP_TIMER
    {
        // Can be ignored, because the topic is set correctly once we start a request anyway.
        (void)snprintf(m_response_topic, sizeof(m_response_topic), ATTRIBUTE_RESPONSE_TOPIC, 0U);
    }

    ~Raw_Attribute_Request() override = default;

    /// @brief Requests one or more raw attribute values from the server,
    /// which will call the subscribed raw callback with the attribute key and raw value string without full JSON parsing
    /// @param callback Callback method that will be called with raw attribute values
    /// @param timeout_milliseconds Optional timeout after which the request is seen as failed if no response has been received, default = 0 which means the request will never time out
    /// @return Whether requesting the given callback was successful or not
    bool Raw_Attributes_Request(Raw_Attribute_Callback const & callback, uint32_t const & timeout_milliseconds = 0U) {
#if !THINGSBOARD_ENABLE_DYNAMIC
        if (m_raw_callbacks.size() + 1U > m_raw_callbacks.capacity()) {
            Logger::printfln(MAX_SUBSCRIPTIONS_EXCEEDED, RAW_ATTRIBUTE_REQUEST_SUBSCRIPTIONS, MAX_SUBSCRIPTIONS_TEMPLATE_NAME);
            return false;
        }
#endif // !THINGSBOARD_ENABLE_DYNAMIC

        // Get request ID from client
        size_t * p_request_id = m_get_request_id_callback.Call_Callback();
        if (p_request_id == nullptr) {
            Logger::printfln(REQUEST_ID_NULL);
            return false;
        }
        auto & request_id = *p_request_id;
        request_id++;

        // Update response topic with current request ID
        (void)snprintf(m_response_topic, sizeof(m_response_topic), ATTRIBUTE_RESPONSE_TOPIC, request_id);

        // Subscribe to response topic if not already subscribed
        if (!m_subscribe_topic_callback.Call_Callback(ATTRIBUTE_RESPONSE_SUBSCRIBE_TOPIC)) {
            char message[strlen(SUBSCRIBE_TOPIC_FAILED) + strlen(ATTRIBUTE_RESPONSE_SUBSCRIBE_TOPIC) + 2] = {};
            (void)snprintf(message, sizeof(message), SUBSCRIBE_TOPIC_FAILED, ATTRIBUTE_RESPONSE_SUBSCRIBE_TOPIC);
            Logger::printfln(message);
            return false;
        }

        // Store callback
        m_raw_callbacks.push_back(callback);

#if !THINGSBOARD_USE_ESP_TIMER
        // Set timeout
        m_timeout = timeout_milliseconds;
        m_request_sent_time = millis();
#endif // !THINGSBOARD_USE_ESP_TIMER

        // Send request - just request the specific attribute key
        char request_topic[Helper::detectSize(ATTRIBUTE_REQUEST_TOPIC, request_id)] = {};
        (void)snprintf(request_topic, sizeof(request_topic), ATTRIBUTE_REQUEST_TOPIC, request_id);

        char const * attr_key = callback.Get_Attribute_Key();
        char request_payload[128];
        (void)snprintf(request_payload, sizeof(request_payload), "{\"sharedKeys\":\"%s\"}", attr_key);

        return m_send_json_string_callback.Call_Callback(request_topic, request_payload);
    }

    API_Process_Type Get_Process_Type() const override {
        return API_Process_Type::RAW;
    }

    void Process_Response(char const * topic, uint8_t * payload, unsigned int length) override {
        if (m_raw_callbacks.empty()) {
            return;
        }

        // Perform minimal JSON parsing - only outer level to find attribute keys
        static constexpr size_t OUTER_JSON_SIZE = 512U;
        StaticJsonDocument<OUTER_JSON_SIZE> outer_doc;
        DeserializationError error = deserializeJson(outer_doc, payload, length);
        
        if (error) {
            // Not valid JSON or too complex for outer parse - skip
            Cleanup_Callbacks();
            return;
        }
        
        JsonObjectConst root = outer_doc.as<JsonObjectConst>();
        
        // Check for "shared" wrapper (attribute responses wrap in "shared")
        if (root.containsKey(SHARED_RESPONSE_KEY)) {
            root = root[SHARED_RESPONSE_KEY];
        }
        
        // For each subscribed callback, check if its attribute key exists
        for (auto const & callback : m_raw_callbacks) {
            char const * attr_key = callback.Get_Attribute_Key();
            
            if (Helper::stringIsNullorEmpty(attr_key)) {
                continue;
            }
            
            // Check if this attribute exists in the payload
            if (!root.containsKey(attr_key)) {
                continue;
            }
            
            // Extract raw value substring from payload
            char const * value_start = nullptr;
            size_t value_length = 0;
            
            if (Extract_Attribute_Value((char *)payload, length, attr_key, &value_start, &value_length)) {
                // Call user callback with raw value string
                callback.Call_Callback(attr_key, value_start, value_length);
            }
        }

        // Clear callbacks after processing (one-time request)
        Cleanup_Callbacks();
    }

    void Process_Json_Response(char const * topic, JsonDocument const & data) override {
        // Not used - we process raw payload in Process_Response
    }

    bool Is_Response_Topic_Matching(char const * topic) const override {
        return strncmp(m_response_topic, topic, strlen(m_response_topic)) == 0;
    }

    bool Unsubscribe() override {
        Cleanup_Callbacks();
        return m_unsubscribe_topic_callback.Call_Callback(ATTRIBUTE_RESPONSE_SUBSCRIBE_TOPIC);
    }

    bool Resubscribe_Permanent_Subscriptions() override {
        // Attribute requests are one-time, not permanent
        return true;
    }

#if !THINGSBOARD_USE_ESP_TIMER
    void loop() override {
        // Check for timeout
        if (m_timeout != 0U && !m_raw_callbacks.empty() && millis() - m_request_sent_time > m_timeout) {
            // Request timed out
            Cleanup_Callbacks();
        }
    }
#endif // !THINGSBOARD_USE_ESP_TIMER

    void Initialize() override {
        // Nothing to do
    }

    void Set_Client_Callbacks(Callback<void, IAPI_Implementation &>::function subscribe_api_callback, Callback<bool, char const * const, JsonDocument const &, size_t const &>::function send_json_callback, Callback<bool, char const * const, char const * const>::function send_json_string_callback, Callback<bool, char const * const>::function subscribe_topic_callback, Callback<bool, char const * const>::function unsubscribe_topic_callback, Callback<uint16_t>::function get_receive_size_callback, Callback<uint16_t>::function get_send_size_callback, Callback<bool, uint16_t, uint16_t>::function set_buffer_size_callback, Callback<size_t *>::function get_request_id_callback) override {
        m_subscribe_topic_callback.Set_Callback(subscribe_topic_callback);
        m_unsubscribe_topic_callback.Set_Callback(unsubscribe_topic_callback);
        m_send_json_string_callback.Set_Callback(send_json_string_callback);
        m_get_request_id_callback.Set_Callback(get_request_id_callback);
    }

  private:
    /// @brief Clears internal callback storage after processing (one-time requests)
    void Cleanup_Callbacks() {
        m_raw_callbacks.clear();
    }

    /// @brief Extracts the raw value substring for a specific attribute key from the JSON payload
    /// (Same implementation as Raw_Shared_Attribute_Update)
    bool Extract_Attribute_Value(char * payload, unsigned int length, char const * attr_key, char const ** out_value_start, size_t * out_value_length) {
        // Build search pattern: "attr_key"
        char search_pattern[128];
        (void)snprintf(search_pattern, sizeof(search_pattern), "\"%s\"", attr_key);
        
        // Find the attribute key in the payload
        char * key_pos = strstr(payload, search_pattern);
        if (key_pos == nullptr) {
            return false;
        }
        
        // Move past the key and find the colon
        char * colon_pos = strchr(key_pos + strlen(search_pattern), ':');
        if (colon_pos == nullptr) {
            return false;
        }
        
        // Skip colon and any whitespace
        char * value_start = colon_pos + 1;
        while (value_start < (char*)(payload + length) && (*value_start == ' ' || *value_start == '\t' || *value_start == '\n' || *value_start == '\r')) {
            value_start++;
        }
        
        if (value_start >= (char*)(payload + length)) {
            return false;
        }
        
        // Find the end of the value
        char * value_end = Find_Value_End(value_start, payload + length);
        if (value_end == nullptr) {
            return false;
        }
        
        *out_value_start = value_start;
        *out_value_length = value_end - value_start;
        return true;
    }

    /// @brief Finds the end of a JSON value starting from value_start
    /// (Same implementation as Raw_Shared_Attribute_Update)
    char * Find_Value_End(char * value_start, char * payload_end) {
        if (value_start >= payload_end) {
            return nullptr;
        }
        
        char first_char = *value_start;
        char * p = value_start;
        
        // Handle different JSON value types
        if (first_char == '{') {
            // Object - track brace depth
            int depth = 0;
            bool in_string = false;
            bool escape_next = false;
            
            while (p < payload_end) {
                if (escape_next) {
                    escape_next = false;
                    p++;
                    continue;
                }
                
                if (*p == '\\') {
                    escape_next = true;
                    p++;
                    continue;
                }
                
                if (*p == '"') {
                    in_string = !in_string;
                }
                else if (!in_string) {
                    if (*p == '{') {
                        depth++;
                    }
                    else if (*p == '}') {
                        depth--;
                        if (depth == 0) {
                            return p + 1;
                        }
                    }
                }
                p++;
            }
            return nullptr;
        }
        else if (first_char == '[') {
            // Array - track bracket depth
            int depth = 0;
            bool in_string = false;
            bool escape_next = false;
            
            while (p < payload_end) {
                if (escape_next) {
                    escape_next = false;
                    p++;
                    continue;
                }
                
                if (*p == '\\') {
                    escape_next = true;
                    p++;
                    continue;
                }
                
                if (*p == '"') {
                    in_string = !in_string;
                }
                else if (!in_string) {
                    if (*p == '[') {
                        depth++;
                    }
                    else if (*p == ']') {
                        depth--;
                        if (depth == 0) {
                            return p + 1;
                        }
                    }
                }
                p++;
            }
            return nullptr;
        }
        else if (first_char == '"') {
            // String - find closing unescaped quote
            p++;
            bool escape_next = false;
            
            while (p < payload_end) {
                if (escape_next) {
                    escape_next = false;
                    p++;
                    continue;
                }
                
                if (*p == '\\') {
                    escape_next = true;
                    p++;
                    continue;
                }
                
                if (*p == '"') {
                    return p + 1;
                }
                p++;
            }
            return nullptr;
        }
        else {
            // Number, boolean, or null - find delimiter
            while (p < payload_end) {
                char c = *p;
                if (c == ',' || c == '}' || c == ']' || c == ' ' || c == '\t' || c == '\n' || c == '\r') {
                    return p;
                }
                p++;
            }
            return p;
        }
    }

    Callback<bool, char const * const>                   m_subscribe_topic_callback = {};     // Subscribe mqtt topic client callback
    Callback<bool, char const * const>                   m_unsubscribe_topic_callback = {};   // Unsubscribe mqtt topic client callback
    Callback<bool, char const * const, char const * const> m_send_json_string_callback = {}; // Send json string callback
    Callback<size_t *>                                   m_get_request_id_callback = {};      // Get internal request id callback

    char                                                 m_response_topic[MAX_ATT_REQUEST_TOPIC_SIZE] = {}; // Response topic with request ID
#if THINGSBOARD_ENABLE_DYNAMIC
    Vector<Raw_Attribute_Callback>                       m_raw_callbacks = {};                // Raw attribute callbacks array
#else
    Array<Raw_Attribute_Callback, MaxSubscriptions>      m_raw_callbacks = {};                // Raw attribute callbacks array
#endif // THINGSBOARD_ENABLE_DYNAMIC

#if !THINGSBOARD_USE_ESP_TIMER
    uint32_t                                             m_request_sent_time = {};            // Time when request was sent
    uint32_t                                             m_timeout = {};                      // Timeout in milliseconds
#endif // !THINGSBOARD_USE_ESP_TIMER
};

#endif // Raw_Attribute_Request_h
